import { useEffect, useMemo, useState } from 'react';
import { addCRM, csv, download, loadCRM, makeId, removeCRM, updateCRM, type CRMState } from './crm';

const PIN = import.meta.env.VITE_ADMIN_PIN || 'EXOVIA2026';
const tabs=[['overview','Overview'],['leads','Leads'],['vendors','Vendors'],['customers','Customers'],['events','Events'],['payments','Payments'],['tasks','Tasks']] as const;
type Tab=typeof tabs[number][0];

const UP_EVENT_LOCATIONS=['Lucknow, Uttar Pradesh','Kanpur, Uttar Pradesh','Noida, Uttar Pradesh','Varanasi, Uttar Pradesh'];

function Admin(){
  const [auth,setAuth]=useState(()=>sessionStorage.getItem('exovia-admin-auth')==='1');
  const [pin,setPin]=useState('');
  const [tab,setTab]=useState<Tab>('overview');
  const [data,setData]=useState<CRMState>(loadCRM());
  const [query,setQuery]=useState('');
  const [notice,setNotice]=useState('');
  const refresh=()=>setData(loadCRM());
  useEffect(()=>{const fn=()=>refresh();addEventListener('exovia-crm-change',fn);addEventListener('storage',fn);return()=>{removeEventListener('exovia-crm-change',fn);removeEventListener('storage',fn)}},[]);

  if(!auth) return <div className="adminAuth"><div className="adminAuthCard"><div className="adminBrand">EXOVIA <span>OPERATIONS CENTER</span></div><div className="adminKicker">PRIVATE ADMIN AREA</div><h1>Run the event company.</h1><p>Manage enquiries, vendors, customers, events, payments and operational tasks from one workspace.</p><form onSubmit={e=>{e.preventDefault();if(pin===PIN){sessionStorage.setItem('exovia-admin-auth','1');setAuth(true)}else setNotice('Incorrect admin PIN.')}}><input value={pin} onChange={e=>setPin(e.target.value)} placeholder="Admin PIN" type="password"/><button>Enter Operations Center ↗</button></form>{notice&&<small>{notice}</small>}<a href="/">← Back to Exovia website</a></div></div>;

  const counts={leads:data.leads.length,vendors:data.vendors.length,customers:data.customers.length,events:data.events.length,payments:data.payments.length,tasks:data.tasks.filter(x=>x.status!=='done').length};
  const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),2400)};
  const exportAll=()=>download(`exovia-crm-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2),'application/json');
  const logout=()=>{sessionStorage.removeItem('exovia-admin-auth');setAuth(false)};

  return <div className="adminShell">
    <aside className="adminSide"><a href="/" className="adminLogo">EXOVIA <small>EVENTS</small></a><div className="adminSideTitle">OPERATIONS</div>{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}<span>{id==='overview'?'':(counts as any)[id]}</span></button>)}<div className="adminSideBottom"><a href="/" target="_blank">View website ↗</a><button onClick={exportAll}>Export CRM ↓</button><button onClick={logout}>Sign out</button></div></aside>
    <main className="adminMain"><header className="adminTop"><div><div className="adminKicker">EXOVIA / OPERATIONS CENTER</div><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><div className="adminTopActions"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people, events, city…"/><span className="liveDot">● LIVE LOCAL DATA</span></div></header>{notice&&<div className="adminNotice">{notice}</div>}
      {tab==='overview'&&<Overview data={data} setTab={setTab}/>} 
      {tab==='leads'&&<LeadManager data={data} query={query} flash={flash}/>} 
      {tab==='vendors'&&<VendorManager data={data} query={query} flash={flash}/>} 
      {tab==='customers'&&<CustomerManager data={data} query={query} flash={flash}/>} 
      {tab==='events'&&<EventManager data={data} flash={flash}/>} 
      {tab==='payments'&&<PaymentManager data={data} flash={flash}/>} 
      {tab==='tasks'&&<TaskManager data={data} flash={flash}/>} 
    </main>
  </div>;
}

function Overview({data,setTab}:{data:CRMState;setTab:(t:Tab)=>void}){const total= data.payments.reduce((s,p)=>s+p.amount,0);return <div className="adminContent"><div className="metricGrid">{[['Leads',data.leads.length,'leads'],['Vendors',data.vendors.length,'vendors'],['Customers',data.customers.length,'customers'],['Events',data.events.length,'events'],['Payment records',data.payments.length,'payments'],['Open tasks',data.tasks.filter(t=>t.status!=='done').length,'tasks']].map(x=><button className="metricCard" key={String(x[0])} onClick={()=>setTab(x[2] as Tab)}><small>{x[0]}</small><strong>{x[1]}</strong><span>Open {String(x[0]).toLowerCase()} ↗</span></button>)}</div><div className="adminColumns"><section className="panel"><div className="panelHead"><div><span>RECENT ENQUIRIES</span><h2>Leads that need attention.</h2></div><button onClick={()=>setTab('leads')}>View all ↗</button></div>{data.leads.slice(0,5).map(l=><div className="row" key={l.id}><div><b>{l.name}</b><small>{l.eventType} · {l.city||'No city'}</small></div><em className={`status ${l.status}`}>{l.status}</em></div>)}{!data.leads.length&&<Empty text="Website enquiries will appear here."/>}</section><section className="panel"><div className="panelHead"><div><span>FINANCE</span><h2>Payment register.</h2></div><button onClick={()=>setTab('payments')}>Manage ↗</button></div><div className="bigNumber">₹{total.toLocaleString('en-IN')}</div><p className="muted">Recorded payment activity. Mark records as pending, paid or verified from Payments.</p></section></div><section className="panel"><div className="panelHead"><div><span>EVENT PIPELINE</span><h2>Upcoming operations.</h2></div><button onClick={()=>setTab('events')}>Manage events ↗</button></div><div className="miniGrid">{data.events.slice(0,4).map(e=><div className="eventMini" key={e.id}><b>{e.name}</b><span>{e.date||'Date TBD'} · {e.city||'City TBD'}</span><em>{e.status}</em></div>)}{!data.events.length&&<Empty text="Create your first event."/>}</div></section></div>}

function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function SearchNo({text}:{text:string}){return <div className="empty">No records match “{text}”.</div>}
function LeadManager({data,query,flash}:{data:CRMState;query:string;flash:(s:string)=>void}){const rows=data.leads.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>WEBSITE CRM</span><h2>Event enquiries</h2></div><button onClick={()=>download('exovia-leads.csv',csv(data.leads),'text/csv')}>Export CSV ↓</button></div>{rows.length?rows.map(l=><div className="dataRow" key={l.id}><div className="dataMain"><b>{l.name}</b><span>{l.phone} · {l.eventType} · {l.city||'—'}</span><small>{l.message||'No message'}</small></div><select value={l.status} onChange={e=>{updateCRM('leads',l.id,{status:e.target.value as any});flash('Lead status updated')}}><option>new</option><option>contacted</option><option>qualified</option><option>closed</option></select><button className="danger" onClick={()=>{removeCRM('leads',l.id);flash('Lead removed')}}>×</button></div>):<SearchNo text={query}/>}</section></div>}
function VendorManager({data,query,flash}:{data:CRMState;query:string;flash:(s:string)=>void}){const rows=data.vendors.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>PARTNER CRM</span><h2>Vendor & stall records</h2></div><button onClick={()=>download('exovia-vendors.csv',csv(data.vendors),'text/csv')}>Export CSV ↓</button></div>{rows.length?rows.map(v=><div className="dataRow" key={v.id}><div className="dataMain"><b>{v.business||v.name}</b><span>{v.name} · {v.phone} · {v.category||'Uncategorised'}</span><small>{v.city||'—'} · {v.event||'No event'} · {v.location||'No area'} · {v.packageName||'No package'}</small></div><select value={v.status} onChange={e=>{updateCRM('vendors',v.id,{status:e.target.value as any});flash('Vendor status updated')}}><option>new</option><option>approved</option><option>hold</option><option>rejected</option></select><button className="danger" onClick={()=>{removeCRM('vendors',v.id);flash('Vendor removed')}}>×</button></div>):<SearchNo text={query}/>}</section></div>}
function CustomerManager({data,query,flash}:{data:CRMState;query:string;flash:(s:string)=>void}){const rows=data.customers.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>CUSTOMER CRM</span><h2>Visitor & registration records</h2></div><button onClick={()=>download('exovia-customers.csv',csv(data.customers),'text/csv')}>Export CSV ↓</button></div>{rows.length?rows.map(c=><div className="dataRow" key={c.id}><div className="dataMain"><b>{c.name}</b><span>{c.phone} · {c.interest||'General interest'}</span><small>{c.city||'—'} · {c.event||'No event'} · {c.location||'No area'}</small></div><select value={c.status} onChange={e=>{updateCRM('customers',c.id,{status:e.target.value as any});flash('Customer status updated')}}><option>new</option><option>registered</option><option>attended</option><option>closed</option></select><button className="danger" onClick={()=>{removeCRM('customers',c.id);flash('Customer removed')}}>×</button></div>):<SearchNo text={query}/>}</section></div>}
function EventManager({data,flash}:{data:CRMState;flash:(s:string)=>void}){
  const [open,setOpen]=useState(false);
  const [form,setForm]=useState({name:'',type:'Food & Flea Market',date:'',city:UP_EVENT_LOCATIONS[0],venue:'',capacity:'',status:'live',notes:''});
  const reset=()=>setForm({name:'',type:'Food & Flea Market',date:'',city:UP_EVENT_LOCATIONS[0],venue:'',capacity:'',status:'live',notes:''});
  const create=()=>{if(!form.name.trim()||!form.date.trim())return;addCRM('events',{...form,id:makeId('evt'),createdAt:new Date().toISOString()} as any);reset();setOpen(false);flash('Event published — it is now visible under Live Events')};
  return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>EVENT OPERATIONS</span><h2>Create and publish live events.</h2><p className="panelSub">Set an event to LIVE and it appears on the public website automatically.</p></div><button onClick={()=>setOpen(!open)}>+ New event</button></div>{open&&<div className="inlineForm">
    <label className="wide">Event name<input autoFocus placeholder="e.g. Diwali Food & Flea Market" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
    <label>Event type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Food & Flea Market</option><option>Wedding</option><option>Engagement / Reception</option><option>Corporate Event</option><option>Exhibition / Pop-up</option><option>Festival / Large Event</option><option>Private Party</option><option>Other</option></select></label>
    <label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>
    <label>UP location<select value={form.city} onChange={e=>setForm({...form,city:e.target.value})}>{UP_EVENT_LOCATIONS.map(x=><option key={x}>{x}</option>)}</select></label>
    <label>Venue<input placeholder="Venue / society / ground" value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label>
    <label>Capacity<input placeholder="e.g. 500" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label>
    <label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>live</option><option>planned</option><option>draft</option><option>completed</option></select></label>
    <label className="wide">Public event description / notes<textarea placeholder="This text is shown on the Live Events card and helps search engines understand the event." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
    <div className="publishHint"><b>LIVE means public.</b> This event will immediately appear in the website's Live Events section on this browser.</div>
    <div className="formActions"><button onClick={create}>Create & publish event ↗</button><button className="ghostBtn" onClick={()=>setOpen(false)}>Cancel</button></div>
  </div>}
  {data.events.map(e=><div className="dataRow" key={e.id}><div className="dataMain"><b>{e.name}</b><span>{e.type||'Event'} · {e.date||'Date TBD'} · {e.city||'City TBD'}</span><small>{e.venue||'Venue TBD'} · Capacity {e.capacity||'—'}</small></div><select value={e.status} onChange={x=>{updateCRM('events',e.id,{status:x.target.value as any});flash(x.target.value==='live'?'Event published to Live Events':'Event status updated')}}><option>draft</option><option>planned</option><option>live</option><option>completed</option></select><button className="danger" onClick={()=>{removeCRM('events',e.id);flash('Event removed')}}>×</button></div>)}{!data.events.length&&!open&&<Empty text="Create an event to start your operations pipeline."/>}</section></div>
}
function PaymentManager({data,flash}:{data:CRMState;flash:(s:string)=>void}){const [open,setOpen]=useState(false);const [f,setF]=useState({party:'',type:'vendor',amount:'',reference:'',notes:'',status:'pending'});const create=()=>{if(!f.party||!f.amount)return;addCRM('payments',{...f,id:makeId('pay'),createdAt:new Date().toISOString(),amount:Number(f.amount)} as any);setF({party:'',type:'vendor',amount:'',reference:'',notes:'',status:'pending'});setOpen(false);flash('Payment record created')};return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>FINANCE CONTROL</span><h2>Payments & reconciliation</h2></div><button onClick={()=>setOpen(!open)}>+ Record payment</button></div>{open&&<div className="inlineForm"><label>Party<input value={f.party} onChange={e=>setF({...f,party:e.target.value})}/></label><label>Type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>vendor</option><option>customer</option><option>expense</option></select></label><label>Amount<input type="number" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Reference<input value={f.reference} onChange={e=>setF({...f,reference:e.target.value})}/></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>pending</option><option>paid</option><option>verified</option></select></label><label className="wide">Notes<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="formActions"><button onClick={create}>Save payment</button></div></div>}{data.payments.map(p=><div className="dataRow" key={p.id}><div className="dataMain"><b>₹{p.amount.toLocaleString('en-IN')} · {p.party}</b><span>{p.type} · {p.reference||'No reference'}</span><small>{p.notes||'No notes'}</small></div><select value={p.status} onChange={e=>{updateCRM('payments',p.id,{status:e.target.value as any});flash('Payment status updated')}}><option>pending</option><option>paid</option><option>verified</option></select><button className="danger" onClick={()=>{removeCRM('payments',p.id);flash('Payment removed')}}>×</button></div>)}{!data.payments.length&&!open&&<Empty text="No payment records yet."/>}</section></div>}
function TaskManager({data,flash}:{data:CRMState;flash:(s:string)=>void}){const [title,setTitle]=useState('');const add=()=>{if(!title.trim())return;addCRM('tasks',{id:makeId('task'),createdAt:new Date().toISOString(),title,owner:'Admin',due:'',status:'todo',priority:'medium'});setTitle('');flash('Task added')};return <div className="adminContent"><section className="panel"><div className="panelHead"><div><span>DAILY OPERATIONS</span><h2>Tasks & follow-ups</h2></div><div className="quickAdd"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add a task…" onKeyDown={e=>e.key==='Enter'&&add()}/><button onClick={add}>Add</button></div></div>{data.tasks.map(t=><div className="dataRow" key={t.id}><div className="dataMain"><b>{t.title}</b><span>{t.owner} · {t.due||'No due date'}</span></div><select value={t.status} onChange={e=>{updateCRM('tasks',t.id,{status:e.target.value as any});flash('Task updated')}}><option>todo</option><option>progress</option><option>done</option></select><button className="danger" onClick={()=>{removeCRM('tasks',t.id);flash('Task removed')}}>×</button></div>)}{!data.tasks.length&&<Empty text="No operational tasks. Add one above."/>}</section></div>}

export default Admin;
